name: Test Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose other OS environments like windows-latest or macos-latest
    steps:
    - uses: actions/checkout@v4  # Step 1: Checkout the code

    - name: Set up Python 3.9
      uses: actions/setup-python@v2  # Step 2: Set up Python
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Step 3: Install dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest  # Step 4: Run your tests
